// <auto-generated />
using System;
using Infraestructura.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructura.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Dominio.Entidades.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PaisNacimiento")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PeliculaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PeliculaId");

                    b.ToTable("Actores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Ricardo Darín",
                            PaisNacimiento = 0
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Antonio Banderas",
                            PaisNacimiento = 1
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Jack Nicholson"
                        });
                });

            modelBuilder.Entity("Dominio.Entidades.Pelicula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Peliculas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "En el verano de 1945, se celebra la boda de Connie (Talia Shire) y Carlo Rizzi (Gianni Russo). Connie es la única hija de Don Vito Corleone (Marlon Brando), jefe de una de las familias que ejercen el mando de la Cosa Nostra en la ciudad de Nueva York. Don Vito además tiene otros tres hijos: su primogénito Sonny (James Caan), el endeble Fredo .",
                            Titulo = "El Padrino"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "En 1947, Andy Dufresne (Tim Robbins), un joven banquero, es condenado a cadena perpetua por asesinar a su esposa y su amante. A pesar de declararse inocente, es encarcelado en Shawshank, el penitenciario más duro del estado de Maine. Allí se encontrará con Red Redding (Morgan Freeman), un hombre desilusionado, encarcelado desde hace más de ...",
                            Titulo = "Cadena Perpetua"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "La Segunda Guerra Mundial está a punto de estallar en Europa. Mientras tanto, Guido llega a un pueblo italiano con la intención de abrir una librería. Allí se enamora de la novia de un fascista italiano, Dora. Ésta sucumbirá a sus encantos y Guido consigue que se case con él. De la bonita unión nace un pequeño que tendrá que vivir en ...",
                            Titulo = "La vida es bella"
                        });
                });

            modelBuilder.Entity("Dominio.Entidades.Actor", b =>
                {
                    b.HasOne("Dominio.Entidades.Pelicula", null)
                        .WithMany("Reparto")
                        .HasForeignKey("PeliculaId");
                });

            modelBuilder.Entity("Dominio.Entidades.Pelicula", b =>
                {
                    b.Navigation("Reparto");
                });
#pragma warning restore 612, 618
        }
    }
}
